# Generated by Django 4.1.5 on 2023-07-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatars/avatar.jpg', upload_to='avatars/', verbose_name='user avatar'),
        ),
    ]
