# Generated by Django 4.1.5 on 2023-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
